### ISSUE TITLE
Misleading error message when virtualbox is not in path

### ISSUE THREAD

**Issue by eis** [hicknhack-software/ansible-buildbot-example#1]
Doing vagrant up I get

```
C:/Users/xxx/repos/ansible-buildbot-example/Vagrantfile:22:in ``': No such file or directory - VBoxManage guestproperty get 78f137c7-9e2e-4bd7-8676-b071cec00a14 "/VirtualBox/GuestInfo/Net/1/V4/IP" (Errno::ENOENT)
        from C:/Users/xxx/repos/ansible-buildbot-example/Vagrantfile:22:in `block (2 levels) in <top (required)>'
        from C:/Users/xxx/.vagrant.d/gems/gems/vagrant-hostmanager-1.6.1/lib/vagrant-hostmanager/hosts_file/updater.rb:103:in `call'
        from C:/Users/xxx/.vagrant.d/gems/gems/vagrant-hostmanager-1.6.1/lib/vagrant-hostmanager/hosts_file/updater.rb:103:in `get_ip_address'
        from C:/Users/xxx/.vagrant.d/gems/gems/vagrant-hostmanager-1.6.1/lib/vagrant-hostmanager/hosts_file/updater.rb:92:in `get_hosts_file_entry'
        from C:/Users/xxx/.vagrant.d/gems/gems/vagrant-hostmanager-1.6.1/lib/vagrant-hostmanager/hosts_file/updater.rb:86:in `block in update_content'
        from C:/Users/xxx/.vagrant.d/gems/gems/vagrant-hostmanager-1.6.1/lib/vagrant-hostmanager/hosts_file/updater.rb:86:in `map'
        from C:/Users/xxx/.vagrant.d/gems/gems/vagrant-hostmanager-1.6.1/lib/vagrant-hostmanager/hosts_file/updater.rb:86:in `update_content'
        from C:/Users/xxx/.vagrant.d/gems/gems/vagrant-hostmanager-1.6.1/lib/vagrant-hostmanager/hosts_file/updater.rb:76:in `update_file'
        from C:/Users/xxx/.vagrant.d/gems/gems/vagrant-hostmanager-1.6.1/lib/vagrant-hostmanager/hosts_file/updater.rb:35:in `update_guest'
        from C:/Users/xxx/.vagrant.d/gems/gems/vagrant-hostmanager-1.6.1/lib/vagrant-hostmanager/action/update_all.rb:34:in `block in call'
        from C:/Users/xxx/.vagrant.d/gems/gems/vagrant-hostmanager-1.6.1/lib/vagrant-hostmanager/action/update_all.rb:31:in `each'
        from C:/Users/xxx/.vagrant.d/gems/gems/vagrant-hostmanager-1.6.1/lib/vagrant-hostmanager/action/update_all.rb:31:in `call'
        from C:/APPS/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/APPS/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from C:/APPS/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/APPS/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/provision.rb:80:in `call'
        from C:/APPS/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/APPS/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:15:in `call'
        from C:/APPS/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
        from C:/APPS/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/set_name.rb:50:in `call'
```

Fix was to add Virtualbox into path, as that is where vboxmanage command is. Error message should be more intuitive.

**Comment by arBmind** [comment]
This seems to be triggered by our hack to retrieve the ip address of the vm in the Vagrantfile.
We so far had no issue with this.
I don't know if Vagrant now has a better option to do this.

Thx for pointing out the workaround.
