### ISSUE TITLE
remote WinRM command parse error

### ISSUE THREAD

**Issue by eis** [hicknhack-software/ansible-buildbot-example#2]
I get this error on both starting up and shutting down:

```
==> winslave1-vm: Attempting graceful shutdown of VM...
An error occurred executing a remote WinRM command.

Shell: powershell
Command: hostname
if ($?) { exit 0 } else { if($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 1 } }
Message: Unable to parse WinRM response: #<REXML::ParseException: Missing end tag for 'br' (got "p")
Line: 3
Position: 224
Last 80 unconsumed characters:
>
C:/APPS/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rexml/parsers/baseparser.rb:338:in `pull_event'
C:/APPS/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rexml/parsers/baseparser.rb:183:in `pull'
C:/APPS/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rexml/parsers/treeparser.rb:22:in `parse'
C:/APPS/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rexml/document.rb:287:in `build'
C:/APPS/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/rexml/document.rb:43:in `initialize'
C:/APPS/HashiCorp/Vagrant/embedded/gems/gems/winrm-1.3.3/lib/winrm/http/response_handler.rb:42:in `new'
C:/APPS/HashiCorp/Vagrant/embedded/gems/gems/winrm-1.3.3/lib/winrm/http/response_handler.rb:42:in `response_xml'
```

Any ideas on how to proceed?
Running on Windows 7, Git shell.

**Comment by arBmind** [comment]
This again seems like an Vagrant issue.
I am no expert for Vagrant, we just use it here.
Sorry to leave you hanging here.

**Comment by eis** [comment]
Finally found the reason for this. I had proxy defined, which will cause the issue explained here: https://github.com/mitchellh/vagrant/issues/6273

Workaround was to unset any proxy settings, at least for the time that node is operated with Vagrant.

**Comment by arBmind** [comment]
ok, I close the issue as it seems to be resolved.
